# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(null=True)),
                ('team_work', models.IntegerField(null=True)),
                ('behavioral_skill', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('designation', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to=b'', verbose_name='employee profile')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='emp_rating',
            name='emp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employinfo'),
        ),
    ]
