# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_rating',
            name='emp',
        ),
        migrations.AddField(
            model_name='employinfo',
            name='behavioral_skill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employinfo',
            name='performance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employinfo',
            name='team_work',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='emp_rating',
        ),
    ]
