# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160829_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employinfo',
            name='behavioral_skill',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='employinfo',
            name='performance',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='employinfo',
            name='team_work',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
