# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to=b'', verbose_name='Product Image')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_updated_date', models.DateTimeField(auto_now=True)),
                ('product_comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.ProductComments')),
            ],
        ),
        migrations.AddField(
            model_name='productcomments',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AddField(
            model_name='carttable',
            name='product_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='products.products'),
        ),
    ]
