# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
