# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20160908_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
